# Generated by Django 5.2 on 2025-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
