# Generated by Django 5.2 on 2025-04-15 16:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0002_alter_company_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="contacts",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
