# Generated by Django 5.2 on 2025-04-06 19:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
