# Generated by Django 5.2 on 2025-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_alter_company_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="saved_vacancies",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="candidates.vacancy"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="vacancies",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidates",
                through="candidates.Application",
                to="candidates.vacancy",
            ),
        ),
    ]
