# Generated by Django 5.2 on 2025-04-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_candidate_saved_vacancies_alter_candidate_vacancies"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="current_role",
            field=models.CharField(
                choices=[("C", "Candidate"), ("E", "Employer")],
                default="C",
                max_length=15,
            ),
        ),
    ]
